---
  melted:
    server: localhost
    port: 5250
  playlists:
    base: playlists
    onair: temp/onair
    past: temp/past
    xml: '/home/jmrunge/mbc/mbc-mosto/temp/xml'
    go: 'temp/go/playlist.go'
  filters:
    gamma: 
      filter: gamma 
      properties:
        gamma: 4
    audio: 
      filter: mono
    mosca: 
      filter: watermark
      properties:
        resource: '/home/jmrunge/zirBig.png'
    hora:
      filter: dynamictext
      properties:
        argument: '#time#'
        size: 15
        bgcolour: '0xffffff88'
        geometry: '605/416:50%x50%:100'
        dynamic: 1
    temperatura:
      filter: dynamictext
      properties:
        argument: 'WALLKINTUN'
        size: 12
        read_file: '/home/jmrunge/temperat.ura'
        bgcolour: '0xffffff88'
        geometry: '605/435:50%x50%:100'
        dynamic: 1
  types:
    defecto: programa
    programa:
      filters:
        - gamma
        - audio
        - mosca
        - hora
        - temperatura
    tanda:
      filters:
        - gamma
        - audio
    basico:
      filters:
        - mosca
